title: Who Wins the Future
description: Power, progress, and who benefits from change
url: https://whowinsthefuture.github.io

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache


minimal_mistakes_skin: dark

author:
  name: Who Wins the Future
exclude:
  - README.md

