title: Who Wins the Future
description: Power, progress, and who benefits from change

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: dark

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide

markdown: kramdown
header:
  overlay: false

defaults:
  - scope:
      path: ""
    values:
      header:
        show: false
